// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_predict_predict_post
 */
export type BodyPredictPredictPost = {
    /**
     * Input
     */
    input: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PredictOutput
 */
export type PredictOutput = {
    /**
     * Label
     */
    label: string;
    /**
     * Probability Blight
     */
    probability_blight: number;
    /**
     * Probability Common Rust
     */
    probability_common_rust: number;
    /**
     * Probability Gray Leaf Spot
     */
    probability_gray_leaf_spot: number;
    /**
     * Probability Healthy
     */
    probability_healthy: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type PredictPredictPostData = {
    body: BodyPredictPredictPost;
    path?: never;
    query?: never;
    url: '/predict';
};

export type PredictPredictPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PredictPredictPostError = PredictPredictPostErrors[keyof PredictPredictPostErrors];

export type PredictPredictPostResponses = {
    /**
     * Successful Response
     */
    200: PredictOutput;
};

export type PredictPredictPostResponse = PredictPredictPostResponses[keyof PredictPredictPostResponses];
